### ISSUE TITLE
Why restrict vaccination, test and recovery group properties to one item?

### ISSUE THREAD

**Issue by andypandy47** [ehn-dcc-development/ehn-dcc-schema#110]
Hi there,

As with the new changes added into v1.3.0, its my understanding that the vaccination, test and recovery group properties are all restricted to one item each. I am a bit confused by this as they are defined as arrays, which initially indicated that multiple medical events could be encoded in a single barcode. With this change however, citizens will require a barcode per vaccination, test and recovery event.

Just wanted to ask what the justification was for this? I feel this may make things more complicated for the user and from what I can see, there wouldn't be any issues around QR code capacity as the character count is relatively small and multiple events have a minor impact.

Thanks

**Comment by dslmeinte** [comment]
The “1-event rule” is a result of an EU regulation - I'll provide a link later, if I can manage. I think the general reasoning was one of simplification to avoid not meeting deadlines because of complexity.

Originally, multi-event DCCs were envisioned (I think - that's “before my time”), which explains the arrays. These didn't get changed in 1.3.0 because of backwards compatibility (and a lot of test data relying on the array-format), and also because it gives the possibility to go back to multi-event in the future, in case it's absolutely needed.

(My €0.02.)

**Comment by gabywh** [comment]
I guess you try reading the FAQ?
https://github.com/ehn-dcc-development/ehn-dcc-schema/wiki/FAQ#why-are-the-certificate-type-entries-specified-as-an-array

**Comment by gabywh** [comment]
> The “1-event rule” is a result of an EU regulation 

It is the result of a clarification to the EU regs provided by DG Just.

> Originally, multi-event DCCs were envisioned (I think - that's “before my time”), which explains the arrays.

Correct. And they would still be of value for a couple of MS.

> These didn't get changed in 1.3.0 because of backwards compatibility (and a lot of test data relying on the array-format), and also because it gives the possibility to go back to multi-event in the future, in case it's absolutely needed.

Possibility for future expansion is one reason: open-closed principle - O in SOLID e.g. https://en.wikipedia.org/wiki/SOLID

**Comment by gabywh** [comment]
Thanks for the use case, of which there are also others even within the EU. Issue discussed many times.

The DCC Schema was initially designed to support multiple combinations of vacc, test and recovery -> which is why there is this "strange" remnant of an array but with min 1 and max 1 in the current DCC Schema.

Statement by Directorate General Justice ("EU legal") stated clearly: only one record EITHER vacc OR test OR recovery per QR Code permissible. So that's how it is.

You may also find the FAQ of use, in particular: https://github.com/ehn-dcc-development/ehn-dcc-schema/wiki/FAQ#why-are-the-certificate-type-entries-specified-as-an-array

HTH.

**Comment by michaelmaguire** [comment]
> Statement by Directorate General Justice ("EU legal") stated clearly: only one record EITHER vacc OR test OR recovery per QR Code permissible. So that's how it is.

Thanks. Do you have a reference to the EU legal statement and a contact. They work for us (as in "we the people"), so we should just ask them.

**Comment by gabywh** [comment]
> > Statement by Directorate General Justice ("EU legal") stated clearly: only one record EITHER vacc OR test OR recovery per QR Code permissible. So that's how it is.
> 
> Thanks. Do you have a reference to the EU legal statement 

https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32021D1073

> and a contact (i.e. in my software company "the business").

Is an EU regulation so:
*  if inside the EU, then follow up with your EU rep (good place to start may be your Member State Ministry of Health)
* if outside the EU, then your "local" European External Action Service might be a good place to start e.g. https://eeas.europa.eu/headquarters/headquarters-homepage_en 

> They work for us (as in "we the people"), so we should just inform them of the problems this is creating and ask them to reconsider.

Already done - which is where the clarification came from.

I appreciate you may not have been involved in the discussions at the time, but you're not saying anything new here or suggesting anything that hasn't already been tried: "been there, done that"

> I was previously an EU citizen, and I'm still married to one - I'm happy to follow it up.

Feel free :)

**Comment by gabywh** [comment]
> "Just arrived in YVR and although I am fully vaccinated they are making me do a hotel quarantine with my kids because my LU Euronorm vaccination pass only has vaccination information for the second vaccine on it. Fair warning. This was an extremely expensive mistake."

As ever: liability is on the traveller to check the rules for the destination - covid-19 changes nothing in that respect.
Two sites that may prove useful:
https://www.traveldoc.aero/
https://reopen.europa.eu/en

**Comment by michaelmaguire** [comment]
> Feel free :)

Great. Can you please pass along the contact office details?  I.e. a person and a phone number or email.
