### ISSUE TITLE
Field Clarification Required - Member State of Vaccination/Test vs Country of Certificate Issuance

### ISSUE THREAD

**Issue by psavva** [ehn-dcc-development/ehn-dcc-schema#111]
Dear @gabywh 

I would please like to raise a question as to clarify the usage of the fields "Member State of Vaccination" and "Member State of Test" and in contrast to the Country that issues the certificate.

We have the following scenario in Cyprus:
A Cypriot citizen may reside in the United States of America, or in the United Kingdom.
That citizen is vaccinated in the US or UK (or another country not participating in the EUDCC solution)

The Cypriot Citizen may request that a Vaccination Certificate is issued to him/her.
The Ministry of Health will collect all/any evidences of the Vaccination, and if approved, will proceed to issue a Certificate of Vaccination in Cyprus.

How is the scenario handled in the EUDCC solution?
The confusions starts with the "Country of Vaccination" vs Country that Issued the certificate.
The current specification does not necessarily specify the country of issuance in a separate field, and the Country of Vaccination is used as the Country of Issuance of the Certificate.

If the country the vaccination was administered was the United States, and the Certificate must be issued for him in Cyprus, as he/she is a Cypriot citizen and has the right to partake in the EU Digital Covid Certificate solution, how will this be recorded on the actual ehn-dcc-schema?

Best Regards
Panayiotis Savva

**Comment by psavva** [comment]
@SchulzeStTSI  I see that the Verification app is also using the logic in the new Business Rules module that the "Country of Vaccination" = "Issuing Country".

Please review the above scenario, as I believe there is perhaps a gap in the current design and must be adjusted to cater for the above.

Best Regards
Panayiotis Savva

**Comment by gabywh** [comment]
Summary, as recently discussed and with reference to: https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.0/DCC.Types.schema.json
* `v / co` - country of vaccination, in general ISO-3166 alpha-2 (with a couple of allowed exceptions)
* `v / is` - issuer - free text field, typically would be a member state Ministry of Health (or equivalent), but no constraints as such - is a free text field

Country for issuer is your point: e.g. Ministry of Health, Cyprus as opposed to, say, Ministry of Health, Italy. Well you could place that (maybe ISO-3611 alpha-2) directly in the `v / is` field but of course this is still free-form as it is "simply" a string of free text. 

Note that country issuing the certificate is already known in the CWT (signer), so that is another option - and a guaranteed one, too. I suspect therefore that you do not need an additional field in the DCC to carry this information, although it could certainly be viewed as an enhancement. That said, same different in two different places almost always goes out of sync at some point, despite best intentions, so probably best to just country of issuance from one known good location: the CWT.

**Comment by kruzikh** [comment]
@gabywh: but this is not answering the question. If the country of vaccination is Kosovo, we currently don't have a two letter code in our valuset. Eurostat is using a provisional code XK for Kosovo (https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Tutorial:Country_codes_and_protocol_order#Codes_and_names_of_EFTA_countries). Maybe, we should create a change request.

**Comment by gabywh** [comment]
Yet another example of where we need to extend the country-2-codes.json. QED.

**Comment by gabywh** [comment]
@kruzikh two separate issues here - by far the more difficult is the one I answered. 
Adding a country code to country-2-codes.json is a trivial matter (or should be).

**Comment by gabywh** [comment]
Added FAQ entry: https://github.com/ehn-dcc-development/ehn-dcc-schema/wiki/FAQ#country-code-and-issuer
